TOP=../..

include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE
#=============================

#=============================
# Build the IOC application

# kepco.dbd will be created and installed
DBD += kepco.dbd
kepco_DBD += base.dbd

include $(TOP)/configure/RULES


